server:
  port: 8090
  servlet:
    context-path: /reading
spring:
  application:
    name: reading-service
  mongodb:
    uri: mongodb://root:123456@localhost:27017/reading-service?authSource=admin
  data:
    mongodb:
      auto-index-creation: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: reading-service
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.devteria.reading.dto.KafkaBookEvent

app:
  service:
    post:
      url: http://localhost:8083/post
    book:
      url: http://localhost:8087/book

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
