server:
  port: 8082
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  mongodb.uri: mongodb://root:123456@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

notification:
  email:
    api-key: ${BREVO_API_KEY}
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

app:
  services:
    profile:
      url: http://localhost:8081/profile

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
