server:
  port: 8086
  servlet:
    context-path: /search

spring:
  application:
    name: search-service

  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: search-service
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.devteria.search.dto.KafkaBookEvent


app:
  services:
    book:
      url: ${BOOK_SERVICE_URL:http://localhost:8087/book}
    post:
      url: ${POST_SERVICE_URL:http://localhost:8083/post}
    group:
      url: ${GROUP_SERVICE_URL:http://localhost:8089/group}

jwt:
  signerKey: "${JWT_SIGNER_KEY}"

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health,info
