server:
  port: 8086
  servlet:
    context-path: /search
spring:
  application:
    name: search-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: search-service
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.devteria.search.dto.KafkaBookEvent


app:
  services:
    book :
      url : http://localhost:8087/book
    post:
      url: http://localhost:8083/post
    group:
      url: http://localhost:8089/group
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
