server:
  port: 8085
  servlet:
    context-path: /chat

spring:
  application:
    name: chat-service

  mongodb:
    uri: ${MONGODB_URI:mongodb://root:123456@localhost:27017/chat-service?authSource=admin}

  data:
    mongodb:
      auto-index-creation: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: chat-service
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.devteria.chat.dto.FriendEventMessage
        spring.json.use.type.headers: false


app:
  services:
    profile:
      url: ${PROFILE_SERVICE_URL:http://localhost:8081/profile}
    identity:
      url: ${IDENTITY_SERVICE_URL:http://localhost:8080/identity}
    friend:
      url: ${FRIEND_SERVICE_URL:http://localhost:8088/friend}

jwt:
  signerKey: "${JWT_SIGNER_KEY}"

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health,info
